channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - statsmodels
  - scikit-learn
  - tensorflow
  - pydub
  - SpeechRecognition
  - opencv-python
  - pocketsphinx
  - openai
  - r-base
  - r-essentials
  - r-tidyverse
  - r-psych
  - r-ggally
  - r-ggcorrplot
  - r-mosaic
  - texinfo
