channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - statsmodels
  - r-base=4.1.3
  - r-tidyverse
  - r-psych
  - r-pracma
  - r-ggally
  - r-ggcorrplot
  - r-mosaic
